// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP_l5cLVtjhgj131ujSvUrLrxJAnzrFNg',
    appId: '1:375579372380:web:7d93cc455d14dead29af99',
    messagingSenderId: '375579372380',
    projectId: 'dalel-8e669',
    authDomain: 'dalel-8e669.firebaseapp.com',
    storageBucket: 'dalel-8e669.firebasestorage.app',
    measurementId: 'G-4PCHR61LVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8K2iSHXU8vl6rr778GeXYFcX74XUdck0',
    appId: '1:375579372380:android:190ce92ef009246429af99',
    messagingSenderId: '375579372380',
    projectId: 'dalel-8e669',
    storageBucket: 'dalel-8e669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy1NLJlgvYBBj5hnyqXp8rGHESImTi40E',
    appId: '1:375579372380:ios:cc6e09c80cfaf22229af99',
    messagingSenderId: '375579372380',
    projectId: 'dalel-8e669',
    storageBucket: 'dalel-8e669.firebasestorage.app',
    iosBundleId: 'com.siraj.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy1NLJlgvYBBj5hnyqXp8rGHESImTi40E',
    appId: '1:375579372380:ios:85dbe2a5503c582629af99',
    messagingSenderId: '375579372380',
    projectId: 'dalel-8e669',
    storageBucket: 'dalel-8e669.firebasestorage.app',
    iosBundleId: 'com.siraj.dalel.macos',
  );
}
